### ISSUE TITLE
crash on kubuntu 18.04

### ISSUE THREAD

**Issue by zhanglongqi** [Zren/plasma-applet-eventcalendar#215] opened 2021-02-09 03:53 UTC
```
Error loading QML file: file:///home/longqi/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/main.qml:121:37: Type PopupView unavailable
file:///home/longqi/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/PopupView.qml:289:3: Type TimerView unavailable
file:///home/longqi/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/TimerView.qml:42:5: Cannot assign to non-existent property "icon"
```

![image](https://user-images.githubusercontent.com/956693/107313429-7513bd80-6acd-11eb-8ef7-d78a2ceadc51.png)

**Comment by zhanglongqi** [comment] 2021-02-09 03:55
X-KDE-PluginInfo-Version=73

**Comment by Zren** [comment] 2021-02-09 15:35
Duplicate of Issue #153. Kubuntu 18.04 and Plasma 5.12.x is no longer supported by this widget. See the following comment to see how to install an older version of the widget:

https://github.com/Zren/plasma-applet-eventcalendar/issues/153#issuecomment-730508702

**Closed** 2021-02-09 15:35 UTC
