### ISSUE TITLE
Google Calendar sync fail (HTTP Error 401 : Unauthorized)

### ISSUE THREAD

**Issue by amiwrpremium** [Zren/plasma-applet-eventcalendar#178] opened 2020-11-10 21:40 UTC
![Screenshot_20201111_011004](https://user-images.githubusercontent.com/39862677/98736896-b0adc700-23ba-11eb-90ff-9fc8d420afad.png)

**Comment by INGCRENGIFO** [comment] 2020-11-10 21:49
#171

**Comment by Zren** [comment] 2020-11-11 00:41
I'm currently trying to fix a quota limit in Issue 171 caused by a few users who haven't upgraded in a year. I plan to ship an update by Friday at the latest which should re-enable Google Calendar sync.

Also, this is a duplicate of #177 so I'm closing this.

**Closed by Zren** 2020-11-11 00:41 UTC
