### ISSUE TITLE
Failed to load QML on Qt 5.14

### ISSUE THREAD

**Issue by kidonng** [Zren/plasma-applet-eventcalendar#111] opened 2019-12-23 00:42 UTC
KDE Plasma: 5.17.4
KDE Framework: 5.65.0
Qt: 5.14.0
Distro: Arch Linux 5.4.6-zen-1-1-zencjk

```
Failed to load QML files: file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/main.qml:100:37: Type PopupView unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/PopupView.qml:337:4: Type AgendaView unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaView.qml:71:15: Type AgendaListItem unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaListItem.qml:194:15: Type AgendaEventItem unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaEventItem.qml:253:4: Type EditEventForm unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/EditEventForm.qml:85:5: Type DurationSelector unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DurationSelector.qml:24:2: Type DateTimeSelector unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateTimeSelector.qml:27:2: Type DateSelector unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateSelector.qml:63:33: Cannot assign object of type "T.Popup" to property of type "Popup_QMLTYPE_323*" as the former is neither the same as the latter nor a sub-class of it.
```

**Comment by Zren** [comment] 2019-12-23 02:26
Duplicate of #99. Should be fixed in the just released v66, which I just updated on AUR.

**Closed by Zren** 2019-12-23 02:26 UTC
