### ISSUE TITLE
Reminders before events

### ISSUE THREAD

**Issue by Zakgeki** [Zren/plasma-applet-eventcalendar#220] opened 2021-02-17 18:23 UTC
Is there a way to make it so that the widget notifies me of an event before the event occurs? Google calendar appears to have this setting unique to each event. Would it be trivial to add this functionality

**Comment by Zakgeki** [comment] 2021-02-17 20:14
I've been digging through the code, and it isn't difficult to get it to send a notification before an event occurs. I'm currently figuring out how to add configuration options so that it can be enabled/disabled and the reminder time before an event starts can be changed.

**Comment by gmm96** [comment] 2021-03-12 15:46
That's definitely a great feature this calendar should also support!

**Comment by Zren** [comment] 2021-03-13 20:02
I'm not sure if Issue #1 is referring to Google "Reminders" which is a different product like Google "Tasks" (Issue #57). So I won't mark this as a duplicate of that.

**Closed** 2021-03-13 20:05 UTC
