### ISSUE TITLE
Smaller tha the original calendar

### ISSUE THREAD

**Issue by TheRussianHetzer** [Zren/plasma-applet-eventcalendar#120] opened 2020-02-11 19:24 UTC
![imagen](https://user-images.githubusercontent.com/60941836/74270651-df075480-4d0b-11ea-94b8-e543bda6cde7.png)
The original plasmoid is larger. I tried to enlarge the letter from the time format. I have also noticed that the separation between the first and second rows is greater. I can barely distinguish the letters.

**Comment by michaldybczak** [comment] 2020-02-15 07:13
I think that the bug I experienced also is the same one, although I had different settings.

Basically what happened, I updated the system and after reboot, calendar fonts became unusually small. I had DATE, TIME format and DATE stayed large, while TIME became smaller and oddly looking (not matching DATE font, spacing, etc.).

This is how it looked before (ignore the doubled layer background bug, it was issue with late, it's already fixed but I made this screenshot for that purpose then):
![Screenshot-2020-01-29-21-18-33](https://user-images.githubusercontent.com/10132958/74583774-d2fcea80-4fca-11ea-85ec-4c4a1722c160.png)

This is how it looked after update:
![Screenshot-2020-02-14-19-35-07](https://user-images.githubusercontent.com/10132958/74583703-24f14080-4fca-11ea-860f-c692d675385d.png)

I use latte as a panel so when windows get maximized, panel becomes solid, currently with a dark theme, so what I also noticed is that with maximized windows, TIME was covered by a huge shadow from the below of the panel's edge (that doesn't produce any shadow by default...). This doesn't happen with other calendars, other widgets. It's specific to Event Calendar after the update.

![Screenshot-2020-02-14-19-35-54](https://user-images.githubusercontent.com/10132958/74583714-47835980-4fca-11ea-9ef5-886f429e6e37.png)

In that state Event Calendar is unusable, so I switched to Chili Calendar.

Here is my system info:

Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.0
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.5.3-2-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 7,6 GiB

This is my pacman log from mentioned update and somewhere there is a package that caused this (I removed packages that I know and am sure that did not cause it like snapd, chromium, electron, etc.):

```
[2020-02-14T17:40:58+0100] upgraded systemd-sysvcompat (244.2-2 -> 244.3-1)
[2020-02-14T17:40:57+0100] upgraded semver (7.1.2-1 -> 7.1.3-1)
[2020-02-14T17:40:57+0100] upgraded python2-lxml (4.4.2-1 -> 4.5.0-1)
[2020-02-14T17:40:57+0100] upgraded python2-html2text (2019.8.11-3 -> 2019.8.11-4)
[2020-02-14T17:40:57+0100] upgraded python2-setuptools (1:44.0.0-1 -> 2:44.0.0-1)
[2020-02-14T17:40:57+0100] upgraded python2-packaging (20.0-1 -> 20.1-1)
[2020-02-14T17:40:57+0100] upgraded python-zipp (1.0.0-1 -> 2.2.0-2)
[2020-02-14T17:40:57+0100] upgraded python-pyinotify (0.9.6-6 -> 0.9.6-7)
[2020-02-14T17:40:57+0100] upgraded python-lxml (4.4.2-1 -> 4.5.0-1)
[2020-02-14T17:40:57+0100] upgraded python-cffi (1.13.2-2 -> 1.14.0-1)
[2020-02-14T17:40:57+0100] upgraded noto-fonts-emoji (20191016-1 -> 20191016-3)
[2020-02-14T17:40:57+0100] upgraded nfs-utils (2.4.2-1 -> 2.4.3-1)
[2020-02-14T17:40:56+0100] upgraded nfsidmap (2.4.2-1 -> 2.4.3-1)
[2020-02-14T17:40:56+0100] upgraded libcpuid (0.4.1.r29.g5f6a9bf-1 -> 0.4.1.r31.gf2ab8b7-1)
[2020-02-14T17:40:56+0100] upgraded lib32-zstd (1.4.4-1 -> 1.4.4-2)
[2020-02-14T17:40:56+0100] upgraded lib32-wayland (1.17.0-1 -> 1.18.0-1)
[2020-02-14T17:40:56+0100] upgraded lib32-systemd (244.2-1 -> 244.3-1)
[2020-02-14T17:40:56+0100] upgraded kstars (1:3.3.9-1 -> 1:3.4.0-1)
[2020-02-14T17:40:54+0100] upgraded freecell-solver (5.16.0-1 -> 5.18.0-1)
[2020-02-14T17:40:54+0100] upgraded flatpak (1.6.1-1 -> 1.6.2-1)
[2020-02-14T17:40:54+0100] upgraded libmm-glib (1.12.4-1 -> 1.12.6-1)
[2020-02-14T17:40:54+0100] upgraded python-requests (2.22.0-3 -> 2.22.0-4)
[2020-02-14T17:40:54+0100] upgraded python-setuptools (1:44.0.0-1 -> 1:45.2.0-1)
[2020-02-14T17:40:54+0100] upgraded python-packaging (20.0-1 -> 20.1-1)
[2020-02-14T17:40:54+0100] upgraded libarchive (3.4.1-1 -> 3.4.2-1)
[2020-02-14T17:40:52+0100] upgraded polkit (0.116-1.1 -> 0.116-4.1)
[2020-02-14T17:40:52+0100] upgraded js60 (60.9.0-1 -> 60.9.0-2)
[2020-02-14T17:40:51+0100] upgraded systemd (244.2-2 -> 244.3-1)
[2020-02-14T17:40:51+0100] upgraded gmp (6.1.2-3 -> 6.2.0-1)
[2020-02-14T17:40:51+0100] upgraded libldap (2.4.48-2 -> 2.4.49-1)
[2020-02-14T17:40:51+0100] upgraded systemd-libs (244.2-2 -> 244.3-1)
[2020-02-14T17:40:51+0100] upgraded libcap (2.30-1 -> 2.31-1)
```

**Comment by vitovt** [comment] 2020-05-26 21:14
same: space between rows is too large:
![image](https://user-images.githubusercontent.com/315178/82950967-062e1d00-9faf-11ea-96dc-f7f2057f2e50.png)

**Comment by Zren** [comment] 2020-06-26 22:03
Duplicate of Issue #6 which was fixed in v67.

**Closed by Zren** 2020-06-26 22:03 UTC
