### ISSUE TITLE
Wrong date in calendar

### ISSUE THREAD

**Issue by gersonjferreira** [Zren/plasma-applet-eventcalendar#20] opened 2018-06-01 14:48 UTC
System date is correct, but the calendar is marking Today's date as yesterday. See picture.

![image](https://user-images.githubusercontent.com/5455489/40847023-8d725812-6591-11e8-927c-ccc99278486f.png)

This is happening in my Antergos desktop, which runs in my office behind a proxy. On the other hand, my notebook runs Manjaro and it works correctly there.

**Comment by Zren** [comment] 2018-06-01 16:48
Is the calendar "today" showing correctly in Digital Clock? Or is it incorrect too?

**Comment by gersonjferreira** [comment] 2018-06-03 00:32
it is correct in the digital clock. Check the image. The clock on the tray says Jun 1st, while the calendar marks May 31.

Now my Manjaro is also showing the same problem. Clock is correct, calendar is one day delayed.

**Comment by Zren** [comment] 2018-06-03 00:56
I meant, is it correct in the official "digital clock" widget. I did not mean the "time in the panel shown by the Event Calendar widget". The reason I is that there's currently a patch up on phab that might be related. If it was also broken with the official widget, then it means Qt or Plasma is broken and not my widget's code.

* https://phabricator.kde.org/D13222
* https://bugs.kde.org/show_bug.cgi?id=394423

In any case, what timezone are you in?

**Comment by gersonjferreira** [comment] 2018-06-03 01:37
oops... sorry. Yes, it is also wrong on the Digital Clock! See figure attached here. My timezone is São Paulo (Brazil). Do you know if there's a workaround? Or should I just wait for update? It is a minor issue anyway.

![image](https://user-images.githubusercontent.com/5455489/40882336-23fe3f8e-66b5-11e8-8733-b9e6bbc60322.png)

**Comment by Zren** [comment] 2018-06-03 01:50
You'll probably need to wait for the fix to be added to plasma frameworks. After it's added, you'll probably still have to wait for Frameworks to update as it has a monthly update cycle.

**Comment by nivaca** [comment] 2018-06-06 12:22
Same problem here.

**Comment by Zren** [comment] 2018-06-06 13:20
Like I said, it affects all plasma widgets.

https://www.reddit.com/r/kde/comments/8o81dn/calendar_displaying_wrong_highlighted_current/

**Comment by Aetf** [comment] 2018-06-19 18:56
Oh, I just realized there's a new repo for event calendar. I opened the issue in the old repo Zren/plasma-applets#133.

From the issue in old repo:
> Another probably related issue: when clicking on a month, the previous month is selected
> ![output](https://user-images.githubusercontent.com/1519759/41617587-e133ac62-73ce-11e8-80d4-275a4c22370c.gif)

**Comment by Zren** [comment] 2018-06-19 19:22
Note, KDE Frameworks v5.48 (which should have the fix) will be released July 14th. It just barely missed getting into v5.47 and unfortunately it's a monthly release schedule.

Interestingly, I could probably write a workaround, as you can see, the agenda is correctly highlighting the right date. It's just the variable the calendar uses for "today" is incorrect. The problem is that this workaround might cause more bugs...

**Comment by Aetf** [comment] 2018-06-19 19:23
It's not a big deal though... So I guess the best option is to wait for the next release of KDE Framework.

**Comment by testeddoughnut** [comment] 2018-07-06 19:38
I just tested the patch from the phabricator link and can confirm it fixed the issue for me.

**Closed** 2018-09-10 23:56 UTC
