### ISSUE TITLE
Applet doesn't load after Qt updates to version 5.14

### ISSUE THREAD

**Issue by mcaliandro** [Zren/plasma-applet-eventcalendar#112] opened 2019-12-23 10:25 UTC
I've updated my system to Qt version 5.14 and now the applet doesn't load and doesn't show any information after KDE Plasma session is started. The following is the error log of the applet:

```
Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/main.qml:100:37: Type PopupView unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/PopupView.qml:337:4: Type AgendaView unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaView.qml:71:15: Type AgendaListItem unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaListItem.qml:194:15: Type AgendaEventItem unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaEventItem.qml:253:4: Type EditEventForm unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/EditEventForm.qml:85:5: Type DurationSelector unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DurationSelector.qml:24:2: Type DateTimeSelector unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateTimeSelector.qml:27:2: Type DateSelector unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateSelector.qml:63:33: Cannot assign object of type "T.Popup" to property of type "Popup_QMLTYPE_253*" as the former is neither the same as the latter nor a sub-class of it.
```

By downgrading Qt packages to version 5.13, the problem doesn't happen. My operating system is ArchLinux with:
- KDE Plasma version: 5.17.4
- KDE Frameworks version: 5.65.0
- Qt version: 5.14.0

In the following [link](https://pastebin.com/i3YApWkj), I report the pacman logs about the Qt packages updated to 5.14

**Comment by Zren** [comment] 2019-12-23 13:12
Duplicate of #99. Should be fixed in the just released v66, which I just [updated on AUR](https://aur.archlinux.org/packages/plasma5-applets-eventcalendar/) a few hours ago.

Restart plasmashell (relog) to refresh the plasma widget.

**Comment by mcaliandro** [comment] 2019-12-24 12:02
I confirm the issues is fixed with the new version v66. I upgraded my o.s. to the new release of Qt, then  reinstalled the package from AUR. Now the applet works fine. @Zren Thank you for the support.

**Comment by wget** [comment] 2020-01-01 16:44
Plasma reported to me this wasn't working with v66 either. I have just removed the widget from the panel and readded it and now it is working properly.

**Comment by Modelmat** [comment] 2020-01-06 04:03
I am currently running version 66 and Qt 5.14, and even after removing and readding I still see the issue.

**Comment by 0Karakurt0** [comment] 2020-01-08 23:43
Same thing, reinstalling and downgrade to 64 did't worked

**Comment by Zren** [comment] 2020-01-09 00:46
@0Karakurt0 

The issue is caused by the popups added in v64. Rolling back to that version won't fix it. You need v66. Then restart plasma to reload the widget.

> https://github.com/Zren/plasma-applet-eventcalendar/blob/master/Changelog.md#v64---october-6-2019
> Add a more complete edit event form that can edit the location. Editing date/time, or moving the event to another calendar are not yet implemented and are disabled.

**Comment by Modelmat** [comment] 2020-01-09 05:40
I'm running version 66 on Arch Linux and I still get the error.
This has been after 3 days, with multiple restarts.

**Comment by Zren** [comment] 2020-01-09 05:54
Do you have it installed to your home directory too? Eg:

`~/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateSelector.qml`

If so, delete the `~/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/` folder. It's loading that instead of the version installed to `/usr/share/...` managed by `pacman`.

If that doesn't work, edit the `DateSelector.qml` and `TimeSelector.qml` like in this patch:

* https://github.com/Zren/plasma-applet-eventcalendar/commit/54098a036c19509e7daea53ddf1c65962c03df5d
* `/usr/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateSelector.qml`

Then restart plasma.

**Comment by Modelmat** [comment] 2020-01-09 06:23
Oh, it appeared I do. I must've had it installed at one point. Fixed :)

**Closed** 2020-07-27 18:02 UTC
