### ISSUE TITLE
Timer doesn't run using real time, accelerates some times

### ISSUE THREAD

**Issue by Akrai** [Zren/plasma-applet-eventcalendar#168] opened 2020-10-28 10:13 UTC
I left the timer for 20 minutes, timer rang, weird as it only passed about 10 minutes of the clock, i set again the timer and I see that the numbers runs twice as quickly as it should... Then i thought that there are other things that does the same too in plasma, like some animations, when using a higher than 60Hz frequency monitor. I couldn't record what i saw exactly, I was watching a streaming while i saw the timer run twice as fast but when i tried to record it i could only trigger this by moving the cursor, if i leave it still, the time runs fine... I don't know, weird

Video attached as zip as i cannot upload videos here
[simplescreenrecorder-2020-10-28_11.07.57.zip](https://github.com/Zren/plasma-applet-eventcalendar/files/5451103/simplescreenrecorder-2020-10-28_11.07.57.zip)

**Comment by Zren** [comment] 2020-10-28 14:31
Duplicate of #129. The video proof was helpful ty.

**Closed by Zren** 2020-10-28 14:31 UTC
